name: gunshots
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - audioread==2.1.8
  - certifi==2019.11.28
  - cffi==1.13.2
  - cycler==0.10.0
  - decorator==4.4.1
  - h5py==2.9.0
  - joblib==0.14.1
  - kiwisolver==1.1.0
  - librosa==0.7.2
  - llvmlite==0.31.0
  - matplotlib==3.1.1
  - mkl_fft=1.2.0
  - mkl_random=1.1.0
  - mkl-service==2.3.0
  - numba==0.47.0
  - numpy==1.17.4
  - olefile==0.46
  - pandas==0.25.3
  - Pillow
  - PyAudio==0.2.11
  - pycparser==2.19
  - pyparsing==2.4.6
  - python-dateutil==2.8.1
  - pytz==2019.3
  - resampy==0.2.2
  - scikit-learn==0.22.1
  - scipy==1.3.2
  - six==1.13.0
  - pysoundfile=0.10.2
  - pytorch==1.3.1
  - torchvision==0.4.2
  - tornado==6.0.3

    

